Repository Financial-Times/origami-registry-ui, pull requests merged in 2021-07, with the labels that each got.

#599 Update for origami v2 on npm
  .bowerrc
  .github/workflows/test.yml
  bower.json
  package-lock.json
  package.json
  src/main.js
Labels: release:minor, service

#612 Increase first byte timeout to be the same as Herokus
  fastly/terraform/main.tf
Labels: release:patch, service

#613 replace scrumple with esbuild
  package-lock.json
  package.json
Labels: okr, release:patch, service
